### ISSUE TITLE
[bug] Unable to switch to a different Cosmos chain when destination address was entered manually

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Network has not changed.
Error appears in Console:
```
TypeError: gr.getNetworkInfo is not a function
    at switchChain (pb-index-CZxC1Ciq.js:527:68227)
    at selectChain (pb-index-CZxC1Ciq.js:538:7606)
    at selectToChain (pb-index-CZxC1Ciq.js:538:7209)
    at Object.Wr [as onSelect] (pb-index-CZxC1Ciq.js:761:88599)
    at Er (pb-index-CZxC1Ciq.js:761:79279)
    at onClick (pb-index-CZxC1Ciq.js:761:80084)
    at Object.Nb (pb-index-CZxC1Ciq.js:43:10486)
    at Tb (pb-index-CZxC1Ciq.js:43:10655)
    at Ub (pb-index-CZxC1Ciq.js:43:10721)
    at nf (pb-index-CZxC1Ciq.js:43:33594)
```

https://github.com/user-attachments/assets/f9b98e57-6c2f-4746-8044-59369dab701b

### Expected Behavior

Network has been changed and wallet has been disconnected. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/859350d189/ 
2. Prepare to send 5 FTM from Fantom (MetaMask) to Osmosis (Wallet address entered manually)
3. Change Osmosis network to Kujira / Injective 

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask
- Browser: Google Chrome Version 127.0.6533.100 (Official Build) (arm64)
```

**Comment by tsadovska** [comment]
Checked on https://portalbridge.com/ [Mainnet]. Wallet is disconnect in "To" section after user changes destination chain. 


https://github.com/user-attachments/assets/c8d2698c-dc03-44ef-885d-86c7b876c05e

Ticket is closed.
