### ISSUE TITLE
[bug] Sometimes balance on Injective network is not loading

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sometimes balance on Injective network is not loading. Please use this [link](https://drive.google.com/file/d/1uSCxg3TAYwbIbOqjLQulvkYnt8KbN4IW/view?usp=sharing) to view the recording. 

Error in Console:
```
Failed to get token balances TypeError: Failed to fetch
    at value (injected.js:1:5640757)
    at http (pb-index-CxT_S-4x.js:522:16434)
    at HttpClient.execute (pb-index-CxT_S-4x.js:522:19103)
    at Tendermint37Client.detectVersion (pb-index-CxT_S-4x.js:522:94173)
    at Tendermint37Client.connect (pb-index-CxT_S-4x.js:522:93955)
    at CosmosContext.getTmClient (pb-index-CxT_S-4x.js:522:623752)
    at async CosmosContext.getCosmWasmClient (pb-index-CxT_S-4x.js:522:624007)
    at async CosmosContext.getWhForeignAsset (pb-index-CxT_S-4x.js:522:620290)
    at async CosmosContext.getGatewayForeignAsset (pb-index-CxT_S-4x.js:522:618748)
    at async CosmosContext.getForeignAsset (pb-index-CxT_S-4x.js:522:618553)
```

![Screenshot 2024-08-14 at 11 31 35](https://github.com/user-attachments/assets/13b84d61-042e-45be-bb9c-d3826b508106)

### Expected Behavior

Balance is successfully loaded. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/41c5f197e5/ or https://portalbridge.com/
2. Select Injective as source chain
3. Connect Leap wallet

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: Leap
- Browser: Google Chrome Version 127.0.6533.100 (Official Build) (arm64)
```

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/. 
Ticket is closed.
