### ISSUE TITLE
[bug] "Error: Simulation error" when claiming W asset on Solana

### ISSUE THREAD

**Issue by agodlevska** [XLabs/portal-bridge-ui#1021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Transaction fails. 
Error: 
```
Error: Simulation error: {"context":{"apiVersion":"1.18.21","slot":283713440},"value":{"accounts":null,"err":"BlockhashNotFound","innerInstructions":null,"logs":[],"returnData":null,"unitsConsumed":0}}
    at NttManager.simulate (pb-index-BXpITdvM.js:543:121219)
    at async NttManager.signAndSendTransaction (pb-index-BXpITdvM.js:543:121868)
    at async NttManager.receiveMessage (pb-index-BXpITdvM.js:543:107149)
    at async NttManual.redeem (pb-index-BXpITdvM.js:543:126375)
    at async Operator.redeem (pb-index-BXpITdvM.js:543:139006)
    at async Object.Un [as onClick] (pb-index-BXpITdvM.js:770:1327)
``` 

### Expected Behavior

Asset is claimed and transaction completes successfully. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/321a610744/
2. Open Menu > Resume transaction
3. Search for transaction hash 0x83aad5c9d4a57a6ca99b97caf35a98cecbd6194646d85a95ee6b750f03cc8abc (Base)
4. Click on "Claim" button
5. Check if transaction has completed

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask, Phantom
- Browser: Google Chrome Version 127.0.6533.120 (Official Build) (x86_64)
```

### Anything else?

<img width="1439" alt="Screenshot 2024-08-15 at 11 03 21" src="https://github.com/user-attachments/assets/db16dad6-fb91-41bb-b8d9-790646d28bee">

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/. 
Issue is no longer reproducible. 
The manual NTT route is currently unavailable when sending to Solana but transactions are still successfully completing through the automatic NTT route.

- Send tx from: [Optimism](https://optimistic.etherscan.io/tx/0x2c8114c9d34ad61ae19af0f12fc0070885652b3fb97b0aabc389533561329260)
- Send tx to: [Solana](https://solscan.io/tx/5ZYPVvRnuaMEMYHmKgrKwzLysJajvHe2DkCrqjiANGC9BEA2R9Uwk8NA4ACHVemAwcHSYmj3hS9c3d8j56BytojF)
- [Wormholescan](https://wormholescan.io/#/tx/0x2c8114c9d34ad61ae19af0f12fc0070885652b3fb97b0aabc389533561329260)

- Send tx from: [Base](https://basescan.org/tx/0x13fafe127aea2d18813d36e21d11b5e0b2e879605e558cc2d8ed49de269ca3ea)
- Send tx to: [Solana](https://solscan.io/tx/3Mvp2DFnWwDfbYqj25wE464tUYjiczvy5h5EhR3JKbrCE4hJFNEfhgtXJGj8nbMBG59f5ZfEPLUzoavsjfDws4wv)
- [Wormholescan](https://wormholescan.io/#/tx/0x13fafe127aea2d18813d36e21d11b5e0b2e879605e558cc2d8ed49de269ca3ea)
