### ISSUE TITLE
[bug] "Switch to Manual Input" option should not be displayed after account is changed in MetaMask app

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"Switch to Manual Input" option is displayed. 

Please use this [link](https://drive.google.com/file/d/1l2bTDDq3SrYAAq_nqpybGjwcXwWYnGcX/view?usp=sharing) to view the recording. 

An error appears after users enters wallet address manually and clicks on "Claim" button:
```
TypeError: gr.getSigner is not a function
    at registerWalletSigner (pb-index-DqOkNN_q.js:558:68866)
    at Object.Un [as onClick] (pb-index-DqOkNN_q.js:797:1209)
```

![image](https://github.com/user-attachments/assets/e1ecf46c-a8e4-43e0-ad0f-b0804dfe7bac)

### Expected Behavior

"Switch to Manual Input" option is not displayed. 

### Steps To Reproduce

1. Open https://portalbridge.com/
2. Prepare to send 0.00001 WMATIC from Polygon (MetaMask through WalletConnect) to Fantom (MetaMask through WalletConnect)
3. Click on "Approve and proceed with transaction" button
4. Wait until "Claim" button appears
5. Change Account in MetaMask app
6. Click on "Claim" button
7. Accept MetaMask app notification to switch network 
8. Click on "Connect wallet" button on Desktop
9. Check if "Switch to Manual Input" option is displayed

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: MetaMask through WalletConnect
- Browser: Google Chrome Version 127.0.6533.120 (Official Build) (arm64)
```

**Comment by tsadovska** [comment]
Closing the ticket, because "Switch to Manual Input" option currently is not displayed on "Connect wallet" screen.
