### ISSUE TITLE
[bug] Transaction fails with "Wormhole Connect: error completing transfer" error

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Transaction fails. Amount is withdrawn from user's account. 

```
Wormhole Connect: error completing transfer Error: Waiting for transaction 0xe8cf2f6e351da69e8b2b8e545e19ff8373a0e6918c233c04fc6036f58c5b07b0 failed
    at _AptosClient$1.waitForTransactionWithResult (pb-index-CLGBMziP.js:376:20812)
    at async _AptosClient$1.waitForTransaction (pb-index-CLGBMziP.js:376:21164)
    at async signAndSendTransaction (aptos-B71Zyf7w-yr-cGyI2.js:34:301936)
    at async signAndSendTransaction (pb-index-CLGBMziP.js:558:70683)
    at async TBTCRoute.send (pb-index-CLGBMziP.js:566:24546)
    at async Operator.send (pb-index-CLGBMziP.js:570:138919)
    at async Object.Nr [as onClick] (pb-index-CLGBMziP.js:794:35634)
```

![image](https://github.com/user-attachments/assets/f64017d6-df56-47b8-8ffb-c428ea5a7d3f)

### Expected Behavior

Transaction proceeds without error.

### Steps To Reproduce

1. Open https://portalbridge.com/
2. Prepare to send 0.000003 tBTC (Ethereum) from Aptos (Spika) to Base (MetaMask)
3. Click on "Approve and proceed with transaction" button
4. Confirm transaction in extension

### Environment

```markdown
- OS: macOS Sonoma 14.5
- Wallet: Spika, MetaMask
- Browser: Google Chrome
```

### Anything else?

Issue is also reproducible with following scenarios:
*  tBTC transfer from Aptos (Spika) to BSC (MetaMask)

![image](https://github.com/user-attachments/assets/34f0b644-acaf-4180-b8d7-b6b2eae8dd01)

* WMATIC transfer from Aptos (Spika) to Arbitrum (MetaMask)

![image](https://github.com/user-attachments/assets/8bab3c22-3f06-4d5e-ba7a-c8171bf68e07)

* USDC transfer from Aptos (Rise) to Celo (MetaMask)

![image](https://github.com/user-attachments/assets/2ba665e8-7582-416e-a9b9-90c5a6e4912c)

Scenarios Tested OK:
* 0.000003 tBTC transfer from [Polygon](https://polygonscan.com/tx/0xdfb924d7716443961b873937f07b9f7b27baad300eece9c57a2f2793b164d828) (MetaMask) to [BSC](https://bscscan.com/tx/0xb723690243ed9e61d8304ea6cc2d249c93d1cada7e695448e1a0000360fb0e48) (MetaMask) 
* 0.00001 WMATIC transfer from [Klaytn](https://klaytnscope.com/tx/0x44dc2760b56c9c6dc101dcf74de8aa5195328a736929f3cc7e58ea26f81833de) (MetaMask) to [Arbitrum](https://arbiscan.io/tx/0xd8c8ca00e2bcb03db8e76ef01e04ec8ba8103621306a1d5667d778c62ff70b12) (MetaMask)

**Comment by tsadovska** [comment]
Issue will be rechecked after https://github.com/XLabs/portal-bridge-ui/issues/1079 is resolved.

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/. 
Scenarios checked:
* 0.00001 WPOL from Aptos (Pontem) to Arbitrum (MetaMask). Link to [Wormholescan](https://wormholescan.io/#/tx/0x7581b7f19f98897aabb01dd11c747dbd06928a03bb4e0dda6e8f3ca2763b8a9b).
* 0.00001 WBNB from Aptos (Pontem) to Celo (MetaMask). Link to [Wormholescan](https://wormholescan.io/#/tx/0x1375affa5f9aa74bb7c0cacb10ba4755fb8f4bf03544299b7ec3aef16b81d150).

Closing the ticket.
