### ISSUE TITLE
[bug] [Binance] Transaction fails with "ERC20: transfer amount exceeds allowance" error

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Transaction fails.
```
Wormhole Connect: error completing transfer Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: ERC20: transfer amount exceeds allowance", method="estimateGas", transaction={"from":"0xc911CBcdd18B2019A884db5A2Bc7c3a8bfb61370","to":"0xb948a93827d68a82F6513Ad178964Da487fe2BD9","value":{"type":"BigNumber","hex":"0x01bb79faacafa0"},"data":"0xb293f97f000000000000000000000000000000000000000000000000000012309ce540000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000c911cbcdd18b2019a884db5a2bc7c3a8bfb61370000000000000000000000000c911cbcdd18b2019a884db5a2bc7c3a8bfb61370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000040100010000000000000000000000000000000000000000000000000000000000","accessList":null}, error={}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at j1.makeError (pb-index-CmYFFWTy.js:376:47781)
    at j1.throwError (pb-index-CmYFFWTy.js:376:47914)
    at checkError$1 (pb-index-CmYFFWTy.js:386:89769)
    at Web3Provider.<anonymous> (pb-index-CmYFFWTy.js:386:100402)
    at Generator.throw (<anonymous>)
    at Ir (pb-index-CmYFFWTy.js:386:88786)
```

![image](https://github.com/user-attachments/assets/dadf030f-8866-4790-905b-3cef725f3a87)

![IMG_5244](https://github.com/user-attachments/assets/084f9873-942f-497b-bd27-1916eded924b)

### Expected Behavior

Transaction proceeds without error.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/43fc9ff3c0/ on Desktop
2. Prepare to send 0.00002 wstETH from Ethereum (Binance Web3 Wallet) to BNB (Binance Web3 Wallet)
3. Click on "Approve and proceed with transaction" button
4. Click on "Confirm" button in "Approve wstETH Permission" notification

### Environment

```markdown
- OS: macOS Sonoma 14.5, iPhone 11 Pro iOS version 17.6.1
- Wallet: Binance Web3 Wallet
- Browser: Google Chrome Version 128.0.6613.120 (Official Build) (arm64)
```

### Anything else?
Issue was reproduced only once.

Issue is not reproducible on https://portalbridge.com/, transaction completed successfully:
* Send from tx: [Etherscan](https://etherscan.io/tx/0x391e5e91dad475f547f262cc446848290891056bc693d14c80c2d393d6f88138)
* Send to tx: [BscScan](https://bscscan.com/tx/0x187125e758bbecb9d3c26b54caff34ac63e1146d683a995adab08009dc91c70d) 
* Link to [Wormholescan](https://wormholescan.io/#/tx/0x391e5e91dad475f547f262cc446848290891056bc693d14c80c2d393d6f88138)

**Comment by tsadovska** [comment]
Rechecked the issue on https://portalbridge.com/, transaction completed successfully. 
Scenario checked: 0.0001 wstETH transfer from Ethereum (Binance) tto BSC (Binance). Link to [Wormholescan](https://wormholescan.io/#/tx/0x9bc1e87d6587ea4a26f56f2b0fdac6e505c28097478170b66f61089b9e4bb906). 

![Screenshot 2024-11-14 at 17 28 18](https://github.com/user-attachments/assets/6e9b727d-3e28-4896-bd7a-f1eefa066568)


![image](https://github.com/user-attachments/assets/4e108fed-97a5-404f-bc4a-4ccf9fa81f58)
