### ISSUE TITLE
[bug] [Binance] Transaction fails with "Method not found" error

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#1072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Transaction fails. Please use [this link](https://drive.google.com/file/d/1WWAqe5TKgJb9RzaJSA1Tptxsz5jebAf1/view?usp=sharing) to view the recording.
```
Wormhole Connect: error completing transfer Error: Method not found
    at index-DUeY0CCy-DN5ZKFuj.js:415:236830
    at c (index-DUeY0CCy-DN5ZKFuj.js:415:234751)
    at Object.next (index-DUeY0CCy-DN5ZKFuj.js:415:234055)
    at P4 (index-DUeY0CCy-DN5ZKFuj.js:415:233099)
    at u (index-DUeY0CCy-DN5ZKFuj.js:415:233297)
```

![Screenshot 2024-09-13 at 18 07 51](https://github.com/user-attachments/assets/998c3ac2-147f-4c8c-8c3c-7cdc6edb8984)

### Expected Behavior

Transaction proceeds without errors. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/43fc9ff3c0/ 
2. Select Moonbeam network in "From" section (Binance wallet was auto-connected)
3. Select Base network in "To" section (Binance wallet was auto-connected)
4. Select GLMR token
5. Enter Amount, in my case 1
6. Change slider position in "Native gas" section
7. Open Binance mobile app
8. Click on "Approve and proceed with transaction" button

### Environment

```markdown
- OS: macOS Sonoma 14.5, iPhone 11 Pro iOS version 17.6.1
- Wallet: Binance Web3 Wallet
- Browser: Google Chrome Version 128.0.6613.120 (Official Build) (arm64)
```

**Comment by tsadovska** [comment]
Please view ticket https://github.com/wormhole-foundation/wormhole-connect/issues/2964.
