### ISSUE TITLE
[bug] Error "transaction indexing is in progress" when sending from BSC

### ISSUE THREAD

**Issue by agodlevska** [XLabs/portal-bridge-ui#1086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An error message "Error with transfer, please try again" is displayed, despite the transaction being successfully completed and the WBNB arriving in the Avalanche account (by checking transaction history and Avalanche account).

```
Wormhole Connect: error completing transfer Error: could not coalesce error (error={ "code": -32000, "data": "transaction indexing is in progress", "message": "transaction indexing is in progress" }, payload={ "id": 21, "jsonrpc": "2.0", "method": "eth_getTransactionReceipt", "params": [ "0x842126f5ae1f7274d89afe8603806b4280e03b9edb13c519c79f1e5cd759d731" ] }, code=UNKNOWN_ERROR, version=6.13.2)
    at makeError (pb-index-DXSlH2sC.js:269:19452)
    at Pi.getRpcError (pb-index-DXSlH2sC.js:270:212791)
    at Pi.getRpcError (evm-Be_3Z-Hc-Bki2EK4O.js:7:2076)
    at pb-index-DXSlH2sC.js:270:215073
``` 
<img width="1440" alt="Screenshot 2024-09-17 at 16 07 29" src="https://github.com/user-attachments/assets/56552be6-8c97-46b9-b4ee-4f346d173a3e">

### Expected Behavior

The transactions should proceed without any error messages.

### Steps To Reproduce

1. Open https://preview.portalbridge.com/b1f3c5115d/
2. Prepare to send 0.001 BNB from BSC (Rabby) to Avalanche (Rabby)
3. Put "Gas" on 22%
4. Initiate the transfer (automatic route)
5. Observe the error message displayed: "Error with transfer, please try again."
6. Check "Transaction history" and the Avalanche account to confirm that the transaction has started and WBNB has been received into the account

### Environment

```markdown
- OS: macOS Sonoma 14.6.1
- Wallet: Rabby
- Browser: Google Chrome Version 128.0.6613.120 (Official Build) (x86_64)
```

### Anything else?

[Video link. ](https://drive.google.com/file/d/19dZ7rwb9HJ9x_jQXW0WCmJhLQtXTNYzv/view?usp=drive_link)

- Send tx from: [BSC](https://bscscan.com/tx/0x167f379eb2826e328357da3560ef3d2449d8005630f7edf69baf47c0ef2f9d14)
- Send tx to: [Avalanche](https://snowtrace.io/tx/0xc1ebe04ac585444936d01f13446fa11e58f17cca22db4a96e22901f0b8d5a86e?chainid=43114)
- [Wormholescan](https://wormholescan.io/#/tx/0x167f379eb2826e328357da3560ef3d2449d8005630f7edf69baf47c0ef2f9d14)

**Comment by Wesleyleung** [comment]
I seem to be getting similar errors for BNB

<img width="562" alt="Screenshot 2024-09-04 at 8 58 59 PM" src="https://github.com/user-attachments/assets/cd559eac-12f2-44c2-9cdc-49572857afc8">

<img width="1705" alt="Screenshot 2024-09-04 at 8 58 52 PM" src="https://github.com/user-attachments/assets/13bd6f04-cccc-4602-aaf7-9609beb4fdba">

**Comment by tsadovska** [comment]
Reproducible on https://portalbridge.com/.
* Route: NTT: Wormhole + Axelar
* Transaction: 0.0001 wstETH from BSC (Rabby) to Ethereum (Rabby)

```
Wormhole Connect: error completing transfer Error: could not coalesce error (error={ "code": -32000, "data": "transaction indexing is in progress", "message": "transaction indexing is in progress" }, payload={ "id": 11, "jsonrpc": "2.0", "method": "eth_getTransactionReceipt", "params": [ "0x4fe9538b3b1bb2095559b33c5acb99c166ed7f0cec952b64fa0f17585bacd49b" ] }, code=UNKNOWN_ERROR, version=6.13.2)
    at makeError (pb-index-Bk8S0RNv.js:271:19452)
    at Ui.getRpcError (pb-index-Bk8S0RNv.js:272:212791)
    at Ui.getRpcError (evm-SljAss8Z-B6Ctor01.js:7:2076)
    at pb-index-Bk8S0RNv.js:272:215073
```

<img width="1182" alt="image" src="https://github.com/user-attachments/assets/8c1a0c01-f0eb-4f20-8e35-0468e3b12dc3">

**Comment by agodlevska** [comment]
Issue reproducible on https://preview.portalbridge.com/49dc473073/, when sending 0.0001 BNB from BSC (Rabby) to Fantom (Rabby). 

```
Wormhole Connect: error completing transfer Error: could not coalesce error (error={ "code": -32000, "data": "transaction indexing is in progress", "message": "transaction indexing is in progress" }, payload={ "id": 23, "jsonrpc": "2.0", "method": "eth_getTransactionReceipt", "params": [ "0x8b29a24e3d9296afed41244c52ed42e3c1c8fbfa613deb47b7546713eb039b53" ] }, code=UNKNOWN_ERROR, version=6.13.3)
    at makeError (pb-index-B2ANqJWe.js:271:19340)
    at Go.getRpcError (pb-index-B2ANqJWe.js:272:212916)
    at Go.getRpcError (evm-Dx7MGmIO-Y0Tyd2G4.js:7:2047)
    at pb-index-B2ANqJWe.js:272:215198
``` 

Attachment:
<img width="1440" alt="Screenshot 2024-10-11 at 12 14 41" src="https://github.com/user-attachments/assets/a9a75161-ac1d-45ff-ba56-3c9566598de6">

**Comment by agodlevska** [comment]
Issue is reproducible on https://preview.portalbridge.com/0a16bf3ef2/, when sending from 0.0014 BSC (Rabby) to USDC on Optimism (Rabby) via Mayan Swift route. 

<img width="1440" alt="Screenshot 2024-11-11 at 15 49 16" src="https://github.com/user-attachments/assets/aef369a9-a99f-4f77-9f26-e13d16ef083b">

**Comment by agodlevska** [comment]
Issue is no longer reproducible, transactions from BSC with Rabby wallet proceed without any error messages, [Wormholescan](https://wormholescan.io/#/tx/0xb4c65af59ab7ec5eb2730561694e0c40ade25000f4a777eb3c230f9e33b06e96 ).

Closing the ticket. 

Attachment:

<img width="540" alt="Image" src="https://github.com/user-attachments/assets/66217116-ad7f-48aa-95f7-d7e4ded7dd42" />
