### ISSUE TITLE
[bug] Balance is not loading for X Layer network

### ISSUE THREAD

**Issue by agodlevska** [XLabs/portal-bridge-ui#1099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Balance for X Layer network is not loading.

```
Failed to get token balances Error: missing response for request (value=[ { "error": { "code": -32079, "message": "Origin not allowed" }, "id": null, "jsonrpc": "2.0" } ], info={ "payload": { "id": 2, "jsonrpc": "2.0", "method": "eth_getBalance", "params": [ "0xd493066498ace409059fda4c1bcd2e73d8cffe01", "latest" ] } }, code=BAD_DATA, version=6.13.2)
    at makeError (pb-index-Bk8S0RNv.js:271:19452)
    at pb-index-Bk8S0RNv.js:272:214928
``` 
<img width="1440" alt="Screenshot 2024-09-20 at 12 50 28" src="https://github.com/user-attachments/assets/ca7408af-802d-4dcb-9ee6-200a570b021b">

### Expected Behavior

Balance is loading for all tokens.

<img width="1440" alt="Screenshot 2024-09-20 at 12 57 10" src="https://github.com/user-attachments/assets/31fdc038-04cf-447c-b178-93edf73fb640">

### Steps To Reproduce

1. Open https://portalbridge.com/
2. Select X Layer network (MetaMask wallet was automatically connected)
3. Check tokens balances

### Environment

```markdown
- OS: macOS Sonoma 14.6.1
- Wallet: MetaMask, Coinbas
- Browser: Google Chrome Version 129.0.6668.58 (Official Build) (x86_64)
```

**Comment by nodesupport1** [comment]
@agodlevska This could be due to a connection issue or a problem with the MetaMask extension.

**Comment by agodlevska** [comment]
Checked on https://portalbridge.com/. 
Issue is still reproducible, balance for X Layer network is not loading.

From:
```
Failed to get token balances Error: missing response for request (value=[ { "error": { "code": -32079, "message": "Origin not allowed" }, "id": null, "jsonrpc": "2.0" } ], info={ "payload": { "id": 2, "jsonrpc": "2.0", "method": "eth_call", "params": [ { "data": "0x70a08231000000000000000000000000d493066498ace409059fda4c1bcd2e73d8cffe01", "to": "0x5866709f926f26c5870191f40333ac462b917bc0" }, "latest" ] } }, code=BAD_DATA, version=6.13.3)
    at makeError (pb-index-DDkttb0r.js:271:19340)
    at pb-index-DDkttb0r.js:272:215053
``` 

<img width="1440" alt="Screenshot 2024-10-25 at 11 07 04" src="https://github.com/user-attachments/assets/f7171a30-e2ff-4355-abf0-bd40ed802255">

To:
```
Failed to get token balances Error: missing response for request (value=[ { "error": { "code": -32079, "message": "Origin not allowed" }, "id": null, "jsonrpc": "2.0" } ], info={ "payload": { "id": 2, "jsonrpc": "2.0", "method": "eth_getBalance", "params": [ "0xd493066498ace409059fda4c1bcd2e73d8cffe01", "latest" ] } }, code=BAD_DATA, version=6.13.3)
    at makeError (pb-index-DDkttb0r.js:271:19340)
    at pb-index-DDkttb0r.js:272:215053
``` 

<img width="1440" alt="Screenshot 2024-10-25 at 11 07 14" src="https://github.com/user-attachments/assets/0ce6c63b-c846-44ab-8e62-8535c28c5ab4">

**Comment by agodlevska** [comment]
Issue is still reproducible on https://portalbridge.com/. 

Attachment:

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/fe620cf5-8b54-41b0-b0a7-57ff32e010ff" />

**Comment by agodlevska** [comment]
Issue is still reproducible on https://portalbridge.com/. 

```
Failed to get token balances Error: missing response for request (value=[ { "error": { "code": -32079, "data": { "trace_id": "998127b2805feef206a0a3b807909dc1" }, "message": "Origin not allowed" }, "id": null, "jsonrpc": "2.0" } ], info={ "payload": { "id": 2, "jsonrpc": "2.0", "method": "eth_getBalance", "params": [ "0xd493066498ace409059fda4c1bcd2e73d8cffe01", "latest" ] } }, code=BAD_DATA, version=6.13.5)
    at makeError (pb-index-DXWIXWxt.js:267:20032)
    at pb-index-DXWIXWxt.js:268:217925
``` 

Attachment:

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/1ce93201-e00b-4577-a460-a5726bbf3c83" />
