### ISSUE TITLE
[bug] Unable to start a transaction with Bitget wallet via automatic route

### ISSUE THREAD

**Issue by agodlevska** [XLabs/portal-bridge-ui#1221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The transaction fails with an error message:
```
Wormhole Connect: error completing transfer Error: Unable to retrieve PublicClient
    at EthereumWallet.<anonymous> (pb-index-B-mi_hOO.js:633:103973)
    at Generator.next (<anonymous>)
    at $n (pb-index-B-mi_hOO.js:633:62300)
``` 

### Expected Behavior

The transaction should start and process successfully without errors. 

### Steps To Reproduce

1. Attempt to initiate the transaction of 2 GLMR from Moonbeam to BSC
2. Select the option to use automatic route 

### Environment

```markdown
- OS: macOS Sequoia 15.0.1
- Wallet: Bitget
- Browser: Google Chrome Version 131.0.6778.140 (Official Build) (x86_64)
- Preview: https://preview.portalbridge.com/7e1e7d6a3d/
```

### Anything else?

<img width="1440" alt="Screenshot 2024-12-20 at 15 31 37" src="https://github.com/user-attachments/assets/e2f580b1-ebdc-4449-8be7-e386846e127e" />

**Comment by agodlevska** [comment]
The issue is no longer reproducible. The transaction was successfully started on https://preview.portalbridge.com/7e1e7d6a3d/ using the Bitget wallet.

Attachment:
<img width="1440" alt="Screenshot 2024-12-23 at 12 27 18" src="https://github.com/user-attachments/assets/a8a9aaa7-65b8-4ea2-b50a-28d31709305c" />
