### ISSUE TITLE
[QA] Loading does not finish when user clicks on Transfer button when sending WMATIC from Sei to Ethereum (Goerli) 

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#163]
#### Build:
https://testnet.portal-bridge-ui.pages.dev/f148f1e66d/#/transfer  [Testnet]

#### Steps:

1. Select Sei network as Source chain
2. Select Ethereum (Goerli) network as Target chain
3. Connect Keplr wallet
4. Select WMATIC token
5. Type amount, 0.001 
6. Click Next button 
7. Connect Metamask wallet in Step 2 “Target”
8. Click Next button
9. Click “Transfer” button in Step 3 

#### Actual results:

- Loading does not finish

- Sei transactions: 

A583A7239C0AD589117177732B11DE9EAB92B9187B4E7608B80F5FF29C30D34E
93E110712271D2ED87BEBC8AEE5106CADD38943047D1FE201539483DB1BD1062

- Error is displayed in Console

```
Uncaught TypeError: Cannot destructure property 'register' of 'undefined' as it is undefined.
    at e (contentScript.js:509:38712)
    at contentScript.js:510:76
    at async WalletContext.tsx:86:16
```

#### Expected results:
Transaction successfully moves to the next step. 

#### Device:
MacBook Pro, macOS Monterey 12.6.5, Chrome Version 113.0.5672.126 (Official Build) (x86_64) 

#### Attachment:
<img width="1671" alt="Screenshot 2023-05-25 at 14 33 45" src="https://github.com/XLabs/portal-bridge-ui/assets/10746654/159cf262-4903-4f2c-8c9d-d6e1250a9b13">

**Comment by tsadovska** [comment]
Closing the ticket because issue is no longer reproducible. User is able to send WMATIC from Sei to Ethereum (Goerli).
Tx details:

- [Sei](https://sei.explorers.guru/transaction/365BA45A2104682284E794FD90CD873E8F73F5809962ACF0FCED59E24DDA9ED0)

- [Ethereum](https://goerli.etherscan.io/tx/0xa705ee1f888b651753229bc681dab2192ac9bbce6a85bd00296a9984792e7efa)

Attachment:
<img width="1591" alt="Issue-163" src="https://github.com/XLabs/portal-bridge-ui/assets/10746654/bb7570d6-6a6e-47eb-ad7e-9c1126049196">
