### ISSUE TITLE
[bug] User is not able resume transfer through Redeem tab

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

User is not able resume transfer through Redeem tab.

Error is displayed in Console:
```
Error: Error: requested VAA not found in store
    at Zg (getSignedVAAWithRetry.ts:39:13)
    at async Ug (Recovery.tsx:160:21)
    at async Recovery.tsx:300:5
    at async Recovery.tsx:686:35
```

### Expected Behavior

User can resume transfer through Redeem tab.

### Steps To Reproduce

1. Send baseETH (in my example 0.00001) from "Base (Goerli)" to "Ethereum (Goerli)"
2. Connect Metamask wallet
3. Copy transaction ID in Step 3 (example: 0xa0d595483d1e833020d6d7f3939d3a6a6287efefd08bd34f529164edf6289b4b)
4. Navigate to Redeem tab
5. Select "Base (Goerli)" as Source chain
6. Paste tx ID: 0xa0d595483d1e833020d6d7f3939d3a6a6287efefd08bd34f529164edf6289b4b

### Environment

```markdown
- OS: macOS Monterey 
- Wallet: Metamask
- Browser: Google Chrome Version 115.0.5790.114 (Official Build) (x86_64)
```

### Anything else?

Attachment: [Screen recording](https://drive.google.com/file/d/15iwvmZ9cb5RsKqi5LNm7hqAIf4BlrVGT/view?usp=sharing)

![image](https://github.com/XLabs/portal-bridge-ui/assets/10746654/29897ed4-c6a9-4867-b6e5-28aa9d112212)

**Comment by sebastianscatularo** [comment]
So far I could research, the VAA was not emitted, this seems to be an issue on Wormhole Guardian Network for testnet, not a portal bridge issue.

Tx: 0xa0d595483d1e833020d6d7f3939d3a6a6287efefd08bd34f529164edf6289b4b

https://front.staging.wormscan.io/#/search-not-found?q=0xa0d595483d1e833020d6d7f3939d3a6a6287efefd08bd34f529164edf6289b4b&network=TESTNET
