### ISSUE TITLE
[support] Available token balance not reflecting <ticket-11077>

### ISSUE THREAD

**Issue by drisAloma** [XLabs/portal-bridge-ui#575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Operation Details

```markdown
- Source Chain: Evmos 
- Source Chain Wallet: Kepler 
- Target Chain: Ethereum 
- Target Chain Wallet: Metamask 
- Asset Type: token 
- Tx:
```

### Current Behavior

The available tokens tab is not loading up the user balance. The user had initially bridge WETH from Ethereum into Evmos and now attempting to bridge it back to Ethereum.

![image-118](https://github.com/XLabs/portal-bridge-ui/assets/64994788/199058e2-720b-4a52-a57f-ed63795fe52f)
![image-110](https://github.com/XLabs/portal-bridge-ui/assets/64994788/c4d6ee73-202a-4203-8381-e836283a1880)

https://etherscan.io/tx/0x41abaa415209374b780b32ca7fcfbb4a995ca65fe4446dad1d4ce947b8e74791

https://wormholescan.io/#/tx/0x41abaa415209374b780b32ca7fcfbb4a995ca65fe4446dad1d4ce947b8e74791

### Expected Behavior

Load up available token balance 

### Anything else?

Tried on birth versions of the bridge.

Another user is facing similar issue on Osmosis (ticket-10789).

![image-173-1](https://github.com/XLabs/portal-bridge-ui/assets/64994788/885307de-86c3-4be5-a93c-e5bf91acc48d)
![image-64-1](https://github.com/XLabs/portal-bridge-ui/assets/64994788/ccda509c-4907-4a03-b493-d924156ae8af)

**Comment by sebastianscatularo** [comment]
@drisAloma could you provide a developer tool output?

**Comment by drisAloma** [comment]
Okay, will get that from the user now

**Comment by sebastianscatularo** [comment]
@SamantaCasal could you try to reproduce it :)

**Comment by sebastianscatularo** [comment]
@mliu-xlabs seems to me this is a connect/ibc gateway issue, fyi

**Comment by sleepycorgi1** [comment]
Hi could we get an update on this one please ? thank you!

**Comment by sebastianscatularo** [comment]
nothing to share yet, sorry for the inconvenience, I'll post here as soon as we get more info

**Comment by drisAloma** [comment]
Hello, users are experiencing similar issue  on KUJIRA and OSMOSIS now 
![image-122-1](https://github.com/XLabs/portal-bridge-ui/assets/64994788/cdd9f167-1247-4e13-ac15-0d208e33fdd0)
![image-195-1](https://github.com/XLabs/portal-bridge-ui/assets/64994788/2bd39631-f586-4b8e-a8d5-63ec28d5b2af)
![image-158](https://github.com/XLabs/portal-bridge-ui/assets/64994788/63460970-b705-4447-9e5e-bbbb3f4dc857)

**Comment by sleepycorgi1** [comment]
Ticket 2037 Unable to send token from evmos to eth 
![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/313e876a-88c6-4abb-b2dd-08ee596d68e2)
![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/e17bc652-489d-40e8-8c0b-52c4dc0b5b77)

**Comment by yuli-ferna** [comment]
@sleepycorgi1 could you provide a developer tool output?

**Comment by yuli-ferna** [comment]
In the case of kujira  that the problem is on the service side of the rpc we are using @sebastianscatularo 

Console capture:

![image](https://github.com/XLabs/portal-bridge-ui/assets/35125931/b4a70128-ffed-4811-93e8-dda960de5930)

And when I use curl it gives me this error:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Not allowed by CORS<br> &nbsp; &nbsp;at origin (/var/task/src/functions/cors.middleware.js:19:18)<br> &nbsp; &nbsp;at /var/task/node_modules/cors/lib/index.js:219:13<br> &nbsp; &nbsp;at optionsCallback (/var/task/node_modules/cors/lib/index.js:199:9)<br> &nbsp; &nbsp;at corsMiddleware (/var/task/node_modules/cors/lib/index.js:204:7)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/var/task/node_modules/express/lib/router/index.js:328:13)<br> &nbsp; &nbsp;at /var/task/node_modules/express/lib/router/index.js:286:9<br> &nbsp; &nbsp;at Function.process_params (/var/task/node_modules/express/lib/router/index.js:346:12)<br> &nbsp; &nbsp;at next (/var/task/node_modules/express/lib/router/index.js:280:10)<br> &nbsp; &nbsp;at compression (/var/task/node_modules/compression/index.js:220:5)</pre>
</body>
</html>
```

**Comment by sleepycorgi1** [comment]
Ticket 2723 
evmos > SOL

User is able to populate the wrapped SOL on evmos however encounters error when sending back to SOL 
(despite converting it from erc20 to ibc in evmos dashboard already)

User is using chrome , has tried with solflare and phantom wallet 

![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/e3cc3f18-d43f-47eb-add3-a4b7cefbc1c7)
![image](https://github.com/XLabs/portal-bridge-ui/assets/59423378/a3d73a10-5eb6-4844-9ea2-bd3db99185b3)

**Comment by sleepycorgi1** [comment]
> @sleepycorgi1 could you provide a developer tool output?
<img width="760" alt="Screen Shot 2024-01-08 at 10 03 05 pm" src="https://github.com/XLabs/portal-bridge-ui/assets/59423378/5abb4b2c-1218-4c54-b29b-356fd089f5a0">
<img width="754" alt="Screen Shot 2024-01-08 at 10 03 16 pm" src="https://github.com/XLabs/portal-bridge-ui/assets/59423378/1924bb0c-98c9-449e-af2a-0dd988e62230">
<img width="741" alt="Screen Shot 2024-01-08 at 10 03 28 pm" src="https://github.com/XLabs/portal-bridge-ui/assets/59423378/ccbaae34-b615-48aa-9469-d147595e4654">
<img width="742" alt="Screen Shot 2024-01-08 at 10 03 38 pm" src="https://github.com/XLabs/portal-bridge-ui/assets/59423378/210b3d9b-ed6f-4e17-86c6-599bbade8fb7">

Ticket 2908 
Another user trying to send back wBTC from Evmos > ETH 
They have also changed it to an IBC token in the EVMOS dashboard, but the UI errors out as shown in images

**Comment by sebastianscatularo** [comment]
@sleepycorgi1 regarding the Evmos ticket could we open a separated one? the issue related to Kujira balance should be solved, and the Evmos issue seems to be something different than balance not diplayed

**Comment by sleepycorgi1** [comment]
> @sleepycorgi1 regarding the Evmos ticket could we open a separated one? the issue related to Kujira balance should be solved, and the Evmos issue seems to be something different than balance not diplayed
Hi @sebastianscatularo ! have opened a ticket with the evmos related balances here - https://github.com/XLabs/portal-bridge-ui/issues/654 (although i think the issues in this ticket #575 is also related to evmos as well ..) thanks!

**Comment by sebastianscatularo** [comment]
@sleepycorgi1 @drisAloma could you re-check it, we've deployed a fix for it

**Comment by drisAloma** [comment]
Okay cool, will do, thank you!

**Comment by drisAloma** [comment]
One of users just tried and it is the same, waiting to get a response from the others.

Also, a new report came in for transfer from EVMOS but this seems to be related to pending issue with ledger. 
![image-155](https://github.com/XLabs/portal-bridge-ui/assets/64994788/b09c8b2e-6086-4710-b8e7-7484b3159d0d)

**Comment by sleepycorgi1** [comment]
Hi @sebastianscatularo do we have any updates re above  re evmos / ledger issue ^ 

affected tickets :  3953  

would we be able to add MM as a supported wallet possibly for evmos + ledger users?

**Comment by sebastianscatularo** [comment]
no updates @sleepycorgi1, I'm checking all the open tickets at this moment, respect to adding a new wallet, for sure, I'll rise a ticket to our tracking system
