### ISSUE TITLE
[bug] Errors during USDC transfer from Avalanche -> Fantom

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

* Warning to register asset is shown for already registered asset.
* Sometimes Insufficient token allowance error appears in Console after user approves transaction for the first time (noticed 2 times).

```
Error: Insufficient token allowance
    at xk.approve (main.js:2:18213274)
    at async xk.send (main.js:2:18214283)
    at async Vne.send (main.js:37:444181)
    at async Object.send (main.js:37:572335)
    at async Object.onClick (main.js:137:5042)
```
* "MetaMask - RPC Error: Invalid transaction params" error appears in Console after user clicks on Claim button (noticed 1 time)

`MetaMask - RPC Error: Invalid transaction params: specified gasPrice but also included maxFeePerGas, these cannot be mixed {code: -32603, message: 'Invalid transaction params: specified gasPrice but also included maxFeePerGas, these cannot be mixed'}`

### Expected Behavior

Warning to register token should not be shown for already registered token. Transaction should proceed without errors.

### Steps To Reproduce

1. Connect Metamask wallets in From and To sections
2. Prepare to send USDC from Avalanche to Fantom
3. Check if warning to register asset is displayed (actual result: warning to register asset is displayed)
4. Type Amount 0.00212 USDC
5. Click "Approve and proceed with transaction" button (actual result: Sometimes Insufficient token allowance error appears)
6. Click "Approve and proceed with transaction" button again
7. Check if transaction is started (actual result: transaction is started)
8. Click on Claim button (actual result: Metamask RPC error appears)
9. Click on Claim button again
9. Check if transaction is completed

### Environment

```markdown
- OS: macOS 12.7.1 
- Wallet: Metamask
- Browser: Google Chrome Version 120.0.6099.109 (Official Build) (x86_64)
```

### Anything else?

Issue is not reproducible on https://wormhole-connect-mainnet.netlify.app/. Warning to register asset is not displayed when sending USDC from Avalanche to Fantom. Transaction is successfully started from the first attempt. 

![Screenshot 2023-12-18 at 17 19 50](https://github.com/XLabs/portal-bridge-ui/assets/10746654/25388d75-2f74-49eb-b3e5-7142673f5c53)

![image](https://github.com/XLabs/portal-bridge-ui/assets/10746654/81b87054-9027-4cce-800a-1fa9c93882b9)

![Screenshot 2023-12-18 at 17 25 35](https://github.com/XLabs/portal-bridge-ui/assets/10746654/7ac8090c-e395-4503-b626-c39ce42801a2)

Transaction can be successfully completed on https://preview.portalbridge.com/7102d8ccad/ if user clicks on "Approve and proceed with transaction" or Claim button several times.

![image](https://github.com/XLabs/portal-bridge-ui/assets/10746654/8dd45dee-fb4b-49d8-b698-3fcbfd1b12b5)

**Comment by tsadovska** [comment]
Issue is no longer reproducible. Checked on https://portalbridge.com/ [Mainnet].
* Manual Bridge: 0.001 USDC (Avalanche) from [Avalanche](https://avascan.info/blockchain/c/tx/0x474af1e9d7cfe6edeaf860b276a5492878dbf21fd7263612b416c084b0339a6d) (MetaMask) to [Fantom](https://ftmscan.com/tx/0xcb517e5e0849418dc63d2c38070384d9766f38d31bb7b37504bf665783819a76) (MetaMask)
* Automatic Bridge: 0.01 USDC (Avalanche) from [Avalanche](https://avascan.info/blockchain/c/tx/0x0c46f4ac9a942a736fff386b997d3f78759998c7468e304573127d31d790ca48) (MetaMask) to [Fantom](https://ftmscan.com/tx/0x5519012a223f3b2e3498348821bd024ffee752c7c02aed04b78aefa4ca77ea9b) (MetaMask)

Ticket is closed.
