### ISSUE TITLE
[bug] "Error: cannot estimate gas" appears when sending USDC.e for the first time

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"Error: cannot estimate gas" appears when sending USDC.e for the first time. Issue is not reproducible after clicking on "Approve and proceed with transaction" button again. 
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: ERC20: transfer amount exceeds allowance", method="estimateGas", transaction={"from":"0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012","to":"0xCafd2f0A35A4459fA40C0517e17e6fA2939441CA","data":"0x1019d6540000000000000000000000002791bca1f2de4661ed88a30c99a7a9449aa8417400000000000000000000000000000000000000000000000000000000001169c900000000000000000000000000000000000000000000000000000000000024cc000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc70120000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted: ERC20: transfer amount exceeds allowance","data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002845524332303a207472616e7366657220616d6f756e74206578636565647320616c6c6f77616e6365000000000000000000000000000000000000000000000000","cause":null}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at Logger.makeError (pb-index.js:334:46729)
    at Logger.throwError (pb-index.js:334:46862)
    at checkError$1 (pb-index.js:340:114180)
    at Web3Provider.<anonymous> (pb-index.js:340:124788)
    at Generator.throw (<anonymous>)
    at nr (pb-index.js:340:113201)
```

### Expected Behavior

Transaction proceeds without errors. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/ [Mainnet]
2. Prepare to send 1.141193 USDC.e from Polygon (MetaMask) to Celo (MetaMask)
3. Change some native gas token in "Native gas" section
4. Click on "Approve and proceed with transaction" button

### Environment

```markdown
- OS: macOS 14.2.1 (23C71)
- Wallet: MetaMask
- Browser: Google Chrome Version 122.0.6261.112 (Official Build) (arm64)
```

### Anything else?

![image](https://github.com/XLabs/portal-bridge-ui/assets/10746654/7aeeeb76-e1e3-4513-be7b-db9ee6abbde4)

**Comment by tsadovska** [comment]
Issue will be rechecked after https://github.com/XLabs/portal-bridge-ui/issues/1036 is resolved.

**Comment by tsadovska** [comment]
Reproducible on https://portalbridge.com/ when sending USDC.e from Polygon to Base.|

Steps:
1. Select Polygon network and USDC.e token in "From" section (MetaMask wallet is auto-connected)
2. Select Base network and USDC token in "To" section (MetaMask wallet is auto-connected)
3. Select Mayan MCTP route
4. Click on "Review transaction" button
5. Click on "Confirm transaction" button

Actual result: Transaction fails.

```
Error: execution reverted (could not decode reason; invalid string data) (action="estimateGas", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000006408c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000742414c233530380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", reason=null, transaction={ "data": "0x30dedc570000000000000000000000002791bca1f2de4661ed88a30c99a7a9449aa841740000000000000000000000000000000000000000000000000000000000000c1c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000111111125421ca6dc452d289314280a0f8842a6500000000000000000000000000000000000000000000000000000000000001a00000000000000000000000003c499c542cef5e3811e1192ce70d8cc03d5c33590000000000000000000000000000000000000000000000000000000000000c09000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c0000000000000000000000000000000000000000000000000000000000000760000000000000000000000000000000000000000000000000000000000000058807ed2379000000000000000000000000e37e799d5077682fa0a244d46e5649f71457bd090000000000000000000000002791bca1f2de4661ed88a30c99a7a9449aa841740000000000000000000000003c499c542cef5e3811e1192ce70d8cc03d5c3359000000000000000000000000e37e799d5077682fa0a244d46e5649f71457bd090000000000000000000000000654874eb7f59c6f5b39931fc45dc45337c967c30000000000000000000000000000000000000000000000000000000000000c1c0000000000000000000000000000000000000000000000000000000000000b7e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000043c00000000000000000000000000000000000000000000000000041e0003f05120d315a9c38ec871068fec378e4ce78af528c762932791bca1f2de4661ed88a30c99a7a9449aa84174016452bbbe2900000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000e37e799d5077682fa0a244d46e5649f71457bd090000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e37e799d5077682fa0a244d46e5649f71457bd0900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006728e63ef5278c0c7572f40127d09399abe6e1305c08810600020000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000002791bca1f2de4661ed88a30c99a7a9449aa841740000000000000000000000003c499c542cef5e3811e1192ce70d8cc03d5c33590000000000000000000000000000000000000000000000000000000000000c1c00000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000062617a0ddd3d3000000000000000000000000000000000000000000000000000000006728e63e00000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000654874eb7f59c6f5b39931fc45dc45337c967c300000000000000000000000000000000000000000000000000005af3107a400000000000000000000de427b5e4f839880000000000000000000b1fa0becab0000000000000000020258d0c737e01b00000000000000002e74af359e8a03f60000000000000000000000000000000000000000000000066570e36f898bd0d3dc100000000000000004563918244f400000000000000000000006a94d74f4300000000000000000000000000006728e602000000000000000000000da475abf00000000000000000000000000000000000000000000000000000000000000000417d81eb02a5d07a18a4281a1a0633ae74c15d24c89f193be9a3a46604f410a3855046bfa150d32e811cbab8be4de18d29764d84be4657b85e280f02ad8079bb401c0000000000000000000000000000000000000000000000000000000000000080a06c4eca273c499c542cef5e3811e1192ce70d8cc03d5c3359111111125421ca6dc452d289314280a0f8842a65000000001ea79a4f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010494454a5d0000000000000000000000003c499c542cef5e3811e1192ce70d8cc03d5c33590000000000000000000000000000000000000000000000000000000000000c1c0000000000000000000000000000000000000000000000000000000000000b6600000000000000000000000000000000000000000000000000000000000000000000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc70120000000000000000000000000000000000000000000000000000000000000006000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c00000000000000000000000000000000000000000000000000000000", "from": "0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012", "to": "0x0654874eb7F59C6f5b39931FC45dC45337c967c3" }, invocation=null, revert=null, code=CALL_EXCEPTION, version=6.13.3)
    at makeError (pb-index-CEsy7cgU.js:271:19340)
    at getBuiltinCallException (pb-index-CEsy7cgU.js:272:107223)
    at Xu.getBuiltinCallException (pb-index-CEsy7cgU.js:272:108177)
    at Go.getRpcError (pb-index-CEsy7cgU.js:272:211289)
    at Go.getRpcError (evm-Bd2pCSsJ-BxQdXTW1.js:7:2047)
    at pb-index-CEsy7cgU.js:272:215198
```
    
 ```
 Wormhole Connect: error completing transfer Error: execution reverted (could not decode reason; invalid string data) (action="estimateGas", data="0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000006408c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000742414c233530380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", reason=null, transaction={ "data": "0x30dedc570000000000000000000000002791bca1f2de4661ed88a30c99a7a9449aa841740000000000000000000000000000000000000000000000000000000000000c1c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000111111125421ca6dc452d289314280a0f8842a6500000000000000000000000000000000000000000000000000000000000001a00000000000000000000000003c499c542cef5e3811e1192ce70d8cc03d5c33590000000000000000000000000000000000000000000000000000000000000c09000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c0000000000000000000000000000000000000000000000000000000000000760000000000000000000000000000000000000000000000000000000000000058807ed2379000000000000000000000000e37e799d5077682fa0a244d46e5649f71457bd090000000000000000000000002791bca1f2de4661ed88a30c99a7a9449aa841740000000000000000000000003c499c542cef5e3811e1192ce70d8cc03d5c3359000000000000000000000000e37e799d5077682fa0a244d46e5649f71457bd090000000000000000000000000654874eb7f59c6f5b39931fc45dc45337c967c30000000000000000000000000000000000000000000000000000000000000c1c0000000000000000000000000000000000000000000000000000000000000b7e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000043c00000000000000000000000000000000000000000000000000041e0003f05120d315a9c38ec871068fec378e4ce78af528c762932791bca1f2de4661ed88a30c99a7a9449aa84174016452bbbe2900000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000e37e799d5077682fa0a244d46e5649f71457bd090000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e37e799d5077682fa0a244d46e5649f71457bd0900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006728e63ef5278c0c7572f40127d09399abe6e1305c08810600020000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000002791bca1f2de4661ed88a30c99a7a9449aa841740000000000000000000000003c499c542cef5e3811e1192ce70d8cc03d5c33590000000000000000000000000000000000000000000000000000000000000c1c00000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000062617a0ddd3d3000000000000000000000000000000000000000000000000000000006728e63e00000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000654874eb7f59c6f5b39931fc45dc45337c967c300000000000000000000000000000000000000000000000000005af3107a400000000000000000000de427b5e4f839880000000000000000000b1fa0becab0000000000000000020258d0c737e01b00000000000000002e74af359e8a03f60000000000000000000000000000000000000000000000066570e36f898bd0d3dc100000000000000004563918244f400000000000000000000006a94d74f4300000000000000000000000000006728e602000000000000000000000da475abf00000000000000000000000000000000000000000000000000000000000000000417d81eb02a5d07a18a4281a1a0633ae74c15d24c89f193be9a3a46604f410a3855046bfa150d32e811cbab8be4de18d29764d84be4657b85e280f02ad8079bb401c0000000000000000000000000000000000000000000000000000000000000080a06c4eca273c499c542cef5e3811e1192ce70d8cc03d5c3359111111125421ca6dc452d289314280a0f8842a65000000001ea79a4f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010494454a5d0000000000000000000000003c499c542cef5e3811e1192ce70d8cc03d5c33590000000000000000000000000000000000000000000000000000000000000c1c0000000000000000000000000000000000000000000000000000000000000b6600000000000000000000000000000000000000000000000000000000000000000000000000000000000000009631288f4050f7cfbf77b77f8540decf6cfc70120000000000000000000000000000000000000000000000000000000000000006000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c000000000000000000000000f18f923480dc144326e6c65d4f3d47aa459bb41c00000000000000000000000000000000000000000000000000000000", "from": "0x9631288F4050F7CFbf77B77f8540DeCF6cfC7012", "to": "0x0654874eb7F59C6f5b39931FC45dC45337c967c3" }, invocation=null, revert=null, code=CALL_EXCEPTION, version=6.13.3)
    at makeError (pb-index-CEsy7cgU.js:271:19340)
    at getBuiltinCallException (pb-index-CEsy7cgU.js:272:107223)
    at Xu.getBuiltinCallException (pb-index-CEsy7cgU.js:272:108177)
    at Go.getRpcError (pb-index-CEsy7cgU.js:272:211289)
    at Go.getRpcError (evm-Bd2pCSsJ-BxQdXTW1.js:7:2047)
    at pb-index-CEsy7cgU.js:272:215198
```
Expected result: Transaction proceeds without errors.  

![Screenshot 2024-11-04 at 17 22 47](https://github.com/user-attachments/assets/691c0915-a9a4-4b86-b276-ac5b5c006056)

**Comment by tsadovska** [comment]
Closing the ticket, because currently USDC.e transfer from Polygon to Celo is not supported. 

![Image](https://github.com/user-attachments/assets/b8320005-46b1-4270-b828-063de443fd06)


Scenario mentioned in [this comment](https://github.com/XLabs/portal-bridge-ui/issues/771#issuecomment-2455014974) is no longer reproducible. Scenario checked: 1.2 USDC.e transfer from Polygon (MetaMask) to Base (MetaMask). Transaction was successfully started. Please use [this link](https://drive.google.com/file/d/1p2jCXJKRdz3AognmYQGfsSkJP0yuw-7T/view?usp=sharing) to view the recording.
