### ISSUE TITLE
[bug] Transaction fails with "call revert exception" error when sending BONK from BSC to Injective for the first time

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error appears in Console after clicking on "Approve and proceed with transaction" button:
```
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="allowance(address,address)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.makeError (main.js:166:46729)
    at Logger.throwError (main.js:166:46862)
    at Interface.decodeFunctionResult (main.js:167:14689)
    at Contract.<anonymous> (main.js:172:50032)
    at Generator.next (<anonymous>)
    at ln (main.js:172:44684)
```
Transaction was successfully started after clicking on "Approve and proceed with transaction" button again. 

### Expected Behavior

Transaction proceeds without errors. 

### Steps To Reproduce

1. Prepare to send BONK from BSC (MetaMask) to Injective (MetaMask)
2. Click on "Approve and proceed with transaction" button

### Environment

```markdown
- OS: macOS 14.2.1 (23C71)
- Wallet: MetaMask 
- Browser: Google Chrome Version 122.0.6261.112 (Official Build) (arm64)
```

### Anything else?

![Screenshot 2024-03-13 at 12 52 46](https://github.com/XLabs/portal-bridge-ui/assets/10746654/0177ed57-4bc5-4fe5-a638-f7a63fa1a447)

**Comment by tsadovska** [comment]
Transaction has been successfully initiated, there were no "call revert exceptions" in Console. Remaining issue: https://github.com/XLabs/portal-bridge-ui/issues/997.
Ticket is closed.
