### ISSUE TITLE
[bug] First transaction from Evmos fails "TypeError: Failed to fetch"

### ISSUE THREAD

**Issue by AigaD** [XLabs/portal-bridge-ui#792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

First transaction from Evmos network fails, reason `TypeError: Failed to fetch` Second transaction is started.

### Expected Behavior

Transaction is started successfully with a first try

### Steps To Reproduce

1. Prepare to send 0.001 WMATIC from Evmos to BSC
2. Click Approve and proceed with transaction
3. Observe

### Environment

```markdown
- OS: macOS Ventura 13.0.1
- Wallet: Leap, Metamask
- Browser: Chrome Version 121.0.6167.85
- Tested from:
https://wormhole-connect-mainnet.netlify.app/ - Tested OK
https://preview.portalbridge.com/b05f4e9322/# - Tested NOK
https://portalbridge.com/ - Tested NOK
```

### Anything else?

<img width="1327" alt="Screenshot 2024-03-19 at 10 31 06" src="https://github.com/XLabs/portal-bridge-ui/assets/91047061/77e0e328-1305-45ae-90c6-1941c8e68b74">

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/b05f4e9322/#
First transaction from Evmos fails, reason `TypeError: Failed to fetch`
Attachment:

<img width="1276" alt="Screenshot 2024-03-25 at 19 51 54" src="https://github.com/XLabs/portal-bridge-ui/assets/91047061/d7923944-9384-4b4f-bd51-6b673e52572c">

**Comment by AigaD** [comment]
Reproduced from: https://preview.portalbridge.com/8228d00809/#
First transaction from Evmos fails, reason `TypeError: Failed to fetch`
Attachment:

<img width="1298" alt="Screenshot 2024-04-02 at 10 53 01" src="https://github.com/XLabs/portal-bridge-ui/assets/91047061/3e660460-f053-4eba-b329-e8ce51f0296d">

**Comment by tsadovska** [comment]
Reproducible on https://preview.portalbridge.com/8228d00809/ [Mainnet] (v0.2.12-Pbd3e3109b6) when sending 0.00001 WMATIC from Injective (Leap) to Osmosis (Leap). 
```
TypeError: Failed to fetch
    at http (pb-index-Bn_4pseu.js:490:16410)
    at HttpClient.execute (pb-index-Bn_4pseu.js:490:19079)
    at Tendermint37Client.doCall (pb-index-Bn_4pseu.js:490:98426)
    at Tendermint37Client.broadcastTxSync (pb-index-Bn_4pseu.js:490:95891)
    at Oo.broadcastTxSync (pb-index-Bn_4pseu.js:490:109856)
    at Oo.broadcastTx (pb-index-Bn_4pseu.js:490:109669)
    at ik.sendTransaction (cosmos-ySs4DZjY-DMrgS7G2.js:112:137966)
    at async pk (cosmos-ySs4DZjY-DMrgS7G2.js:112:138624)
    at async signAndSendTransaction (pb-index-Bn_4pseu.js:490:777337)
    at async Operator.send (pb-index-Bn_4pseu.js:495:127455)
```
![image](https://github.com/XLabs/portal-bridge-ui/assets/10746654/98a58014-77bc-4fd4-bfbe-c904518ebf0a)

**Comment by agodlevska** [comment]
The issue is no longer relevant after the redesign, Cosmos chains are not available on https://portalbridge.com/.

Ticket can be closed.
