### ISSUE TITLE
[bug] Cannot connect WalletConnect wallet

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An error appears after clicking on "WalletConnect" option:
```
TypeError: Cannot set property signal of [object AbortController] which has only a getter
    at pb-index-DrUOIUci.js:734:9470
    at Ut.addKeyboardEvents (index-BNwGsa-t-j_2IJeAg.js:54:67520)
    at Ut.onOpenModalEvent (index-BNwGsa-t-j_2IJeAg.js:54:66822)
    at index-BNwGsa-t-j_2IJeAg.js:54:66174
    at index-XoQjK7BX-BuyBC5mK.js:7:10982
    at index-XoQjK7BX-BuyBC5mK.js:7:3327
    at io.invoke (pb-index-DrUOIUci.js:733:6920)
    at $o.run (pb-index-DrUOIUci.js:733:1929)
    at pb-index-DrUOIUci.js:734:647
    at io.invokeTask (pb-index-DrUOIUci.js:733:7579)
```

### Expected Behavior

WalletConnect pop-up appears. 

### Steps To Reproduce

1. Open https://preview.portalbridge.com/bceadc8c64/ 
2. Select Avalanche network as source chain
3. Click on "Connect wallet" button
4. Select "WalletConnect" option

### Environment

```markdown
- OS: macOS Sonoma 14.4.1 
- Wallet: WalletConnect
- Browser: Google Chrome Version 124.0.6367.119 (Official Build) (arm64)
```

### Anything else?

https://portalbridge.com/ - Tested OK
https://preview.portalbridge.com/bceadc8c64/  - Tested NOK

![image](https://github.com/XLabs/portal-bridge-ui/assets/10746654/b96d7a67-fbb0-4140-bc04-c2a75d8369db)

**Comment by lvandernoll** [comment]
For me, having this issue in a different codebase, adding the downgraded dependency `zone.js@0.14.2` my codebase fixed this issue

**Comment by tsadovska** [comment]
Issue is no longer reproducible. Checked on https://preview.portalbridge.com/859350d189/ and https://portalbridge.com/.
Closing the ticket.
