### ISSUE TITLE
[bug] Transaction from Aptos fails with "ApiError: Bad Request" error

### ISSUE THREAD

**Issue by tsadovska** [XLabs/portal-bridge-ui#889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Transaction from Aptos fails with "ApiError: Bad Request" error.
```
Wormhole Connect: error completing transfer ApiError: Bad Request
    at catchErrorCodes (pb-index-CYbPcUgW.js:271:63272)
    at pb-index-CYbPcUgW.js:271:63730
```

### Expected Behavior

Transaction proceeds without error.

### Steps To Reproduce

1. Open https://portalbridge.com/
2. Prepare to send 0.0001 WMATIC from Aptos (Spika) to Solana (Phantom)
3. Click on "Approve and proceed with transaction" button

### Environment

```markdown
- OS: macOS Sonoma 14.4.1 
- Wallet: Spika, Phantom
- Browser: Google Chrome Version 125.0.6422.142 (Official Build) (arm64)
```

### Anything else?
Issue is also reproducible with Martian wallet. 

![image](https://github.com/XLabs/portal-bridge-ui/assets/10746654/a417cac4-fc85-4062-813a-f6c3b61e448e)

Issue is not reproducible on https://wormhole-connect-mainnet.netlify.app/ [Mainnet].

![image](https://github.com/XLabs/portal-bridge-ui/assets/10746654/4b38cf9a-0827-47f9-a156-220b660de6dd)

**Comment by tsadovska** [comment]
Issue is no longer reproducible on https://portalbridge.com/ [Mainnet]. 
Scenario checked: 0.0001 WMATIC transfer from Aptos (Spika) to Solana (Phantom). 

* Send from tx: [Aptos Explorer](https://explorer.aptoslabs.com/txn/0xb122398e0dbc069aebda88a65350881cc58fa089e292b45af73856b65db59d72?network=mainnet)
* Send to tx: [Solana Explorer](https://explorer.solana.com/tx/2zfnVygsvMdhZ5Yysa47ivb7A8im4iXBK1FjjGTeeedAtY9AxwX7ss42Wjn4hBvY89jSEYLKgrmGHLRwXKTUZwcC)
* Link to [Wormholescan](https://wormholescan.io/#/tx/22/0000000000000000000000000000000000000000000000000000000000000001/159020)


![image](https://github.com/user-attachments/assets/b41c3301-3d57-4ee0-b025-9bdd4ac32186)


Ticket is closed.
